# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import dungeon_pb2 as dungeon__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dungeon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DungeonServiceStub(object):
    """Service Definition für Multi-User Dungeon
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterPlayer = channel.unary_unary(
                '/dungeon.DungeonService/RegisterPlayer',
                request_serializer=dungeon__pb2.RegisterPlayerRequest.SerializeToString,
                response_deserializer=dungeon__pb2.RegisterPlayerResponse.FromString,
                _registered_method=True)
        self.UnregisterPlayer = channel.unary_unary(
                '/dungeon.DungeonService/UnregisterPlayer',
                request_serializer=dungeon__pb2.UnregisterPlayerRequest.SerializeToString,
                response_deserializer=dungeon__pb2.UnregisterPlayerResponse.FromString,
                _registered_method=True)
        self.MovePlayer = channel.unary_unary(
                '/dungeon.DungeonService/MovePlayer',
                request_serializer=dungeon__pb2.MovePlayerRequest.SerializeToString,
                response_deserializer=dungeon__pb2.MovePlayerResponse.FromString,
                _registered_method=True)
        self.GetPlayerInfo = channel.unary_unary(
                '/dungeon.DungeonService/GetPlayerInfo',
                request_serializer=dungeon__pb2.GetPlayerInfoRequest.SerializeToString,
                response_deserializer=dungeon__pb2.PlayerInfo.FromString,
                _registered_method=True)
        self.GetRoomInfo = channel.unary_unary(
                '/dungeon.DungeonService/GetRoomInfo',
                request_serializer=dungeon__pb2.GetRoomInfoRequest.SerializeToString,
                response_deserializer=dungeon__pb2.RoomInfo.FromString,
                _registered_method=True)
        self.LookAround = channel.unary_unary(
                '/dungeon.DungeonService/LookAround',
                request_serializer=dungeon__pb2.LookAroundRequest.SerializeToString,
                response_deserializer=dungeon__pb2.LookAroundResponse.FromString,
                _registered_method=True)
        self.TakeItem = channel.unary_unary(
                '/dungeon.DungeonService/TakeItem',
                request_serializer=dungeon__pb2.TakeItemRequest.SerializeToString,
                response_deserializer=dungeon__pb2.TakeItemResponse.FromString,
                _registered_method=True)
        self.DropItem = channel.unary_unary(
                '/dungeon.DungeonService/DropItem',
                request_serializer=dungeon__pb2.DropItemRequest.SerializeToString,
                response_deserializer=dungeon__pb2.DropItemResponse.FromString,
                _registered_method=True)
        self.TalkToNPC = channel.unary_unary(
                '/dungeon.DungeonService/TalkToNPC',
                request_serializer=dungeon__pb2.TalkToNPCRequest.SerializeToString,
                response_deserializer=dungeon__pb2.TalkToNPCResponse.FromString,
                _registered_method=True)
        self.AttackNPC = channel.unary_unary(
                '/dungeon.DungeonService/AttackNPC',
                request_serializer=dungeon__pb2.AttackNPCRequest.SerializeToString,
                response_deserializer=dungeon__pb2.AttackNPCResponse.FromString,
                _registered_method=True)
        self.OpenChest = channel.unary_unary(
                '/dungeon.DungeonService/OpenChest',
                request_serializer=dungeon__pb2.OpenChestRequest.SerializeToString,
                response_deserializer=dungeon__pb2.OpenChestResponse.FromString,
                _registered_method=True)
        self.CloseChest = channel.unary_unary(
                '/dungeon.DungeonService/CloseChest',
                request_serializer=dungeon__pb2.CloseChestRequest.SerializeToString,
                response_deserializer=dungeon__pb2.CloseChestResponse.FromString,
                _registered_method=True)
        self.PutInChest = channel.unary_unary(
                '/dungeon.DungeonService/PutInChest',
                request_serializer=dungeon__pb2.PutInChestRequest.SerializeToString,
                response_deserializer=dungeon__pb2.PutInChestResponse.FromString,
                _registered_method=True)
        self.GetFromChest = channel.unary_unary(
                '/dungeon.DungeonService/GetFromChest',
                request_serializer=dungeon__pb2.GetFromChestRequest.SerializeToString,
                response_deserializer=dungeon__pb2.GetFromChestResponse.FromString,
                _registered_method=True)
        self.InspectChest = channel.unary_unary(
                '/dungeon.DungeonService/InspectChest',
                request_serializer=dungeon__pb2.InspectChestRequest.SerializeToString,
                response_deserializer=dungeon__pb2.InspectChestResponse.FromString,
                _registered_method=True)
        self.ReadScroll = channel.unary_unary(
                '/dungeon.DungeonService/ReadScroll',
                request_serializer=dungeon__pb2.ReadScrollRequest.SerializeToString,
                response_deserializer=dungeon__pb2.ReadScrollResponse.FromString,
                _registered_method=True)
        self.CastSpell = channel.unary_unary(
                '/dungeon.DungeonService/CastSpell',
                request_serializer=dungeon__pb2.CastSpellRequest.SerializeToString,
                response_deserializer=dungeon__pb2.CastSpellResponse.FromString,
                _registered_method=True)
        self.ListSpellbook = channel.unary_unary(
                '/dungeon.DungeonService/ListSpellbook',
                request_serializer=dungeon__pb2.ListSpellbookRequest.SerializeToString,
                response_deserializer=dungeon__pb2.ListSpellbookResponse.FromString,
                _registered_method=True)
        self.SendDirectMessage = channel.unary_unary(
                '/dungeon.DungeonService/SendDirectMessage',
                request_serializer=dungeon__pb2.SendDirectMessageRequest.SerializeToString,
                response_deserializer=dungeon__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.SendRoomMessage = channel.unary_unary(
                '/dungeon.DungeonService/SendRoomMessage',
                request_serializer=dungeon__pb2.SendRoomMessageRequest.SerializeToString,
                response_deserializer=dungeon__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.SendBroadcastMessage = channel.unary_unary(
                '/dungeon.DungeonService/SendBroadcastMessage',
                request_serializer=dungeon__pb2.SendBroadcastMessageRequest.SerializeToString,
                response_deserializer=dungeon__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.GetOnlinePlayers = channel.unary_unary(
                '/dungeon.DungeonService/GetOnlinePlayers',
                request_serializer=dungeon__pb2.GetOnlinePlayersRequest.SerializeToString,
                response_deserializer=dungeon__pb2.GetOnlinePlayersResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/dungeon.DungeonService/StreamEvents',
                request_serializer=dungeon__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=dungeon__pb2.GameEvent.FromString,
                _registered_method=True)


class DungeonServiceServicer(object):
    """Service Definition für Multi-User Dungeon
    """

    def RegisterPlayer(self, request, context):
        """Spieler Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterPlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MovePlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoomInfo(self, request, context):
        """Raum Information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookAround(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TakeItem(self, request, context):
        """Interaktionen
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TalkToNPC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttackNPC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenChest(self, request, context):
        """Kisten/Container
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseChest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutInChest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFromChest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectChest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadScroll(self, request, context):
        """Magie System
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CastSpell(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSpellbook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendDirectMessage(self, request, context):
        """Messaging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendRoomMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBroadcastMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOnlinePlayers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Events Stream (Server-to-Client)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DungeonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPlayer,
                    request_deserializer=dungeon__pb2.RegisterPlayerRequest.FromString,
                    response_serializer=dungeon__pb2.RegisterPlayerResponse.SerializeToString,
            ),
            'UnregisterPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterPlayer,
                    request_deserializer=dungeon__pb2.UnregisterPlayerRequest.FromString,
                    response_serializer=dungeon__pb2.UnregisterPlayerResponse.SerializeToString,
            ),
            'MovePlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.MovePlayer,
                    request_deserializer=dungeon__pb2.MovePlayerRequest.FromString,
                    response_serializer=dungeon__pb2.MovePlayerResponse.SerializeToString,
            ),
            'GetPlayerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerInfo,
                    request_deserializer=dungeon__pb2.GetPlayerInfoRequest.FromString,
                    response_serializer=dungeon__pb2.PlayerInfo.SerializeToString,
            ),
            'GetRoomInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoomInfo,
                    request_deserializer=dungeon__pb2.GetRoomInfoRequest.FromString,
                    response_serializer=dungeon__pb2.RoomInfo.SerializeToString,
            ),
            'LookAround': grpc.unary_unary_rpc_method_handler(
                    servicer.LookAround,
                    request_deserializer=dungeon__pb2.LookAroundRequest.FromString,
                    response_serializer=dungeon__pb2.LookAroundResponse.SerializeToString,
            ),
            'TakeItem': grpc.unary_unary_rpc_method_handler(
                    servicer.TakeItem,
                    request_deserializer=dungeon__pb2.TakeItemRequest.FromString,
                    response_serializer=dungeon__pb2.TakeItemResponse.SerializeToString,
            ),
            'DropItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DropItem,
                    request_deserializer=dungeon__pb2.DropItemRequest.FromString,
                    response_serializer=dungeon__pb2.DropItemResponse.SerializeToString,
            ),
            'TalkToNPC': grpc.unary_unary_rpc_method_handler(
                    servicer.TalkToNPC,
                    request_deserializer=dungeon__pb2.TalkToNPCRequest.FromString,
                    response_serializer=dungeon__pb2.TalkToNPCResponse.SerializeToString,
            ),
            'AttackNPC': grpc.unary_unary_rpc_method_handler(
                    servicer.AttackNPC,
                    request_deserializer=dungeon__pb2.AttackNPCRequest.FromString,
                    response_serializer=dungeon__pb2.AttackNPCResponse.SerializeToString,
            ),
            'OpenChest': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenChest,
                    request_deserializer=dungeon__pb2.OpenChestRequest.FromString,
                    response_serializer=dungeon__pb2.OpenChestResponse.SerializeToString,
            ),
            'CloseChest': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseChest,
                    request_deserializer=dungeon__pb2.CloseChestRequest.FromString,
                    response_serializer=dungeon__pb2.CloseChestResponse.SerializeToString,
            ),
            'PutInChest': grpc.unary_unary_rpc_method_handler(
                    servicer.PutInChest,
                    request_deserializer=dungeon__pb2.PutInChestRequest.FromString,
                    response_serializer=dungeon__pb2.PutInChestResponse.SerializeToString,
            ),
            'GetFromChest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFromChest,
                    request_deserializer=dungeon__pb2.GetFromChestRequest.FromString,
                    response_serializer=dungeon__pb2.GetFromChestResponse.SerializeToString,
            ),
            'InspectChest': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectChest,
                    request_deserializer=dungeon__pb2.InspectChestRequest.FromString,
                    response_serializer=dungeon__pb2.InspectChestResponse.SerializeToString,
            ),
            'ReadScroll': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadScroll,
                    request_deserializer=dungeon__pb2.ReadScrollRequest.FromString,
                    response_serializer=dungeon__pb2.ReadScrollResponse.SerializeToString,
            ),
            'CastSpell': grpc.unary_unary_rpc_method_handler(
                    servicer.CastSpell,
                    request_deserializer=dungeon__pb2.CastSpellRequest.FromString,
                    response_serializer=dungeon__pb2.CastSpellResponse.SerializeToString,
            ),
            'ListSpellbook': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSpellbook,
                    request_deserializer=dungeon__pb2.ListSpellbookRequest.FromString,
                    response_serializer=dungeon__pb2.ListSpellbookResponse.SerializeToString,
            ),
            'SendDirectMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDirectMessage,
                    request_deserializer=dungeon__pb2.SendDirectMessageRequest.FromString,
                    response_serializer=dungeon__pb2.SendMessageResponse.SerializeToString,
            ),
            'SendRoomMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRoomMessage,
                    request_deserializer=dungeon__pb2.SendRoomMessageRequest.FromString,
                    response_serializer=dungeon__pb2.SendMessageResponse.SerializeToString,
            ),
            'SendBroadcastMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBroadcastMessage,
                    request_deserializer=dungeon__pb2.SendBroadcastMessageRequest.FromString,
                    response_serializer=dungeon__pb2.SendMessageResponse.SerializeToString,
            ),
            'GetOnlinePlayers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOnlinePlayers,
                    request_deserializer=dungeon__pb2.GetOnlinePlayersRequest.FromString,
                    response_serializer=dungeon__pb2.GetOnlinePlayersResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=dungeon__pb2.StreamEventsRequest.FromString,
                    response_serializer=dungeon__pb2.GameEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dungeon.DungeonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dungeon.DungeonService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DungeonService(object):
    """Service Definition für Multi-User Dungeon
    """

    @staticmethod
    def RegisterPlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/RegisterPlayer',
            dungeon__pb2.RegisterPlayerRequest.SerializeToString,
            dungeon__pb2.RegisterPlayerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterPlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/UnregisterPlayer',
            dungeon__pb2.UnregisterPlayerRequest.SerializeToString,
            dungeon__pb2.UnregisterPlayerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MovePlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/MovePlayer',
            dungeon__pb2.MovePlayerRequest.SerializeToString,
            dungeon__pb2.MovePlayerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlayerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/GetPlayerInfo',
            dungeon__pb2.GetPlayerInfoRequest.SerializeToString,
            dungeon__pb2.PlayerInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoomInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/GetRoomInfo',
            dungeon__pb2.GetRoomInfoRequest.SerializeToString,
            dungeon__pb2.RoomInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookAround(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/LookAround',
            dungeon__pb2.LookAroundRequest.SerializeToString,
            dungeon__pb2.LookAroundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TakeItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/TakeItem',
            dungeon__pb2.TakeItemRequest.SerializeToString,
            dungeon__pb2.TakeItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/DropItem',
            dungeon__pb2.DropItemRequest.SerializeToString,
            dungeon__pb2.DropItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TalkToNPC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/TalkToNPC',
            dungeon__pb2.TalkToNPCRequest.SerializeToString,
            dungeon__pb2.TalkToNPCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AttackNPC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/AttackNPC',
            dungeon__pb2.AttackNPCRequest.SerializeToString,
            dungeon__pb2.AttackNPCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenChest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/OpenChest',
            dungeon__pb2.OpenChestRequest.SerializeToString,
            dungeon__pb2.OpenChestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseChest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/CloseChest',
            dungeon__pb2.CloseChestRequest.SerializeToString,
            dungeon__pb2.CloseChestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutInChest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/PutInChest',
            dungeon__pb2.PutInChestRequest.SerializeToString,
            dungeon__pb2.PutInChestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFromChest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/GetFromChest',
            dungeon__pb2.GetFromChestRequest.SerializeToString,
            dungeon__pb2.GetFromChestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectChest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/InspectChest',
            dungeon__pb2.InspectChestRequest.SerializeToString,
            dungeon__pb2.InspectChestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadScroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/ReadScroll',
            dungeon__pb2.ReadScrollRequest.SerializeToString,
            dungeon__pb2.ReadScrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CastSpell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/CastSpell',
            dungeon__pb2.CastSpellRequest.SerializeToString,
            dungeon__pb2.CastSpellResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSpellbook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/ListSpellbook',
            dungeon__pb2.ListSpellbookRequest.SerializeToString,
            dungeon__pb2.ListSpellbookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendDirectMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/SendDirectMessage',
            dungeon__pb2.SendDirectMessageRequest.SerializeToString,
            dungeon__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendRoomMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/SendRoomMessage',
            dungeon__pb2.SendRoomMessageRequest.SerializeToString,
            dungeon__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendBroadcastMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/SendBroadcastMessage',
            dungeon__pb2.SendBroadcastMessageRequest.SerializeToString,
            dungeon__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOnlinePlayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dungeon.DungeonService/GetOnlinePlayers',
            dungeon__pb2.GetOnlinePlayersRequest.SerializeToString,
            dungeon__pb2.GetOnlinePlayersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dungeon.DungeonService/StreamEvents',
            dungeon__pb2.StreamEventsRequest.SerializeToString,
            dungeon__pb2.GameEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
